services:
  firebase:
    image: spine3/firebase-emulator:latest
    ports:
      - "4000:4000"  # UI
      - "9099:9099"  # Auth
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=0.0.0.0:9099
      - GCP_PROJECT_ID=demo-weallvote
      - ENABLE_UI=true

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - firebase
    volumes:
      - ./app.db:/app.db
    ports:
      - "8080:8080"  # App
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=firebase:9099
      - DATABASE_URL=/app/app.db
      - GCLOUD_PROJECT=demo-weallvote
